version: '3.8'

services:
  ch:
    image: cloudhypervisor:rest
    build:
      context: .
      target: builder
    tty: true
    privileged: true
    command:
      - cloud-hypervisor
      - --api-socket
      - /var/run/ch/cloud-hypervisor.sock
      - --net
      - "tap=,mac=,ip=,mask="
    volumes:
      - ./images:/usr/src/images
      - ./socket:/var/run/ch/
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
